### ISSUE TITLE
dist directory should be there

### ISSUE THREAD

**Issue by bdsword** [josteink/gmailjs-node-boilerplate#1]
As title, I got an error 

```Error: ENOENT: no such file or directory, open 'dist/extension.js'```

when I ran ```npm run build```.

I think you should put or generate the dist fold automatically for the users.

Or at least, you should mention it in README.md.

**Comment by josteink** [comment]
Agreed. I'll try to get it into the build-script, so people wont have to think about it.

**Comment by josteink** [comment]
Should be fixed in https://github.com/josteink/gmailjs-node-boilerplate/commit/fe48e51cbf7f43ef773c84254bbc5917a6e7f9ab.
