### ISSUE TITLE
Manifest V3 host permissions

### ISSUE THREAD

**Issue by bearoxo** [josteink/gmailjs-node-boilerplate#23]
[Manifest V3 host permissions](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#host-permissions)

    "host_permissions": [
        "https://*/*"
    ]

Shouldn't it be like this for manifest V3?

**Comment by josteink** [comment]
The update to V3 was done by @tomer-regev. 

Care to take a look? 🙂

**Comment by josteink** [comment]
I just checked and you're absolutely right. Fixed and closed in https://github.com/josteink/gmailjs-node-boilerplate/commit/4061b938426bc72210e9d8ae8b997398b8c0bde4.

Thanks for reporting!

**Comment by cancan101** [comment]
Why set `host_permissions` to be `"https://*/*"` rather than just `"*://mail.google.com/*"` (from `content_scripts`)?

**Comment by josteink** [comment]
You're probably right. That could probably work too, if all you're interacting with is gmail itself.

But that comes at the cost of having to whitelist all other hosts you want to interact with, for instance when using other external APIs, and that could slow down your prototyping.

And when it comes to priorities for this example repo: The readme has [a clear disclaimer](https://github.com/josteink/gmailjs-node-boilerplate#disclaimer) about this setup not being a "production" hardened in every way possible.

This repo just represents a way to quickly get running with gmail.js and see how it works, without making any other assumptions.
