### ISSUE TITLE
Unable to get this boilerplate to work

### ISSUE THREAD

**Issue by mhatvan** [josteink/gmailjs-node-boilerplate#24]
Both the manifest v2 and v3 branches don't give me any `console.log` output inside Gmail.

Can someone verify that this still works, and I am just doing something wrong?

**Comment by josteink** [comment]
Works for me:
![image](https://user-images.githubusercontent.com/411338/148770079-62157933-5b7d-4924-bc23-d46553115b1b.png)

Did you follow the instructions in the README and actually *build* the extensions before adding it to your browser? It's an easy thing to miss out on, and you wouldn't be the first :smile:

**Comment by mhatvan** [comment]
I realize what my issue was:
Usually, you specify the `dist` folder as base dir for Chrome extensions to keep the bundle size small.
With this boilerplate, it is intended to use the root dir of the project (resulting in 11MB extension size right away)
Some scripts point to the `src` folder and some to the `dist` folder in the `manifest.json` which is additionally confusing.

Also, there is an extension error reported: `Permission 'https://*/*' is unknown or URL pattern is malformed.`

**Comment by josteink** [comment]
Loading and bundling from a common root was a decision to keep things simple and as understandable as possible, without introducing *any* concepts not Gmailjs in the process. 

The latter sounds related to the manifest V3  migration, and I think we already have an issue for that.

**Comment by mhatvan** [comment]
I see, Why the need for a `dist` folder then at all?

Another error reported 3x with different key files by Chrome extension: `This extension includes the key file '.../gmailjs-node-boilerplate/node_modules/public-encrypt/test/test_key.pem'. You probably don't want to do that.`

**Comment by josteink** [comment]
Dist folder because that is where people usually put bundled scripts. 

Just consider that this is _not meant as an example of a production extension_, merely a way to show how to embed Gmail.is in a web-extension generally, and make it easy to play around with and test the Gmail.is API without having to build anything on your own first. 

If you have ideas for how those goals can be improved in this repo, feel free to issue a PR 🙂

In the meantime... I guess this issue can be considered solved and closed now? Sounds like you got things working, right?

**Comment by mhatvan** [comment]
Sure, but if we upload the whole folder as chrome extension, we have `extension.js` file, etc. twice in the file tree, since it exists in `src` and `dist`.

I guess I will also play around with a locally downloaded `jquery` + `gmail.js` version etc instead of using `node_modules`.

I will get the client project going and once I find time I can contribute to this repo ;)

Definitely, thanks for the fast support. You might want to specify this in the `Readme.md` though to `load unpacked` the base dir vs `dist` dir.

**Comment by josteink** [comment]
I'm not sure what you mean by locally downloaded as opposed to using node_modules, but whatever rocks your boat. They get bundled into dist none the less :)

Also keep in mind that right now, using npm to obtain and update gmail.js is the preferred way of doing things and if you have issues later not doing things the standard way can complicate the diagnosis process.

**Comment by josteink** [comment]
Just FYI: Readme updated and disclaimer added. 

Thanks for the suggestion!
