### ISSUE TITLE
how to use background service worker from gmailjs extension.

### ISSUE THREAD

**Issue by petegordon** [josteink/gmailjs-node-boilerplate#27]
I've been working on trying to understand the background service worker and get it to work in the startExtension example. And, I can't seem to get it. I have it working in the content_script--but I'm getting stuck with how to best utilize it in my extension. Ultimately, I want a button that invokes chrome.identity.launchWebAuthFlow. I'll keep working on it later, and post if/when I come up with a solution. Thanks.

https://developer.chrome.com/docs/extensions/mv3/messaging/

**Comment by josteink** [comment]
I honestly haven't tested using background-workers yet.

I've implemented an extension though which passed messages through all the "regular" pages though:

* web page -> window.postMessage() sends to content-page, window.onmessage for incoming messages.
* content page -> window.onmessage to receive incoming messages from web page, can use chrome.* APIs to send to background page
* background page -> use chrome.* APIs to listen for messages

It takes quite a bit of boilerplate code to get seamless messages back and forth, but it shouldn't be magic. 

How much of that is changed or needs to be changed to support background workers, I have no idea :)

**Comment by petegordon** [comment]
Thanks. I’ll be spending time on it today and see if I can come up with the needed boilerplate to demonstrate background service message passing with the startExtension gmailJS usage. I’ll share what I find.

Pete
________________________________
