### ISSUE TITLE
gmail.get.email_data() error 404

### ISSUE THREAD

**Issue by o-x-y-g-e-n** [josteink/gmailjs-node-boilerplate#3]
`gmail
{get: {…}, observe: {…}, check: {…}, tools: {…}, tracker: {…}, …}
gmail.tools.extract_email_address()
undefined
gmail.get.displayed_email_data_async()
undefined
VM19558:1 GET https://mail.google.com/mail/u/0/?ui=2&ik=&rid=undefined&view=cv&th=1621dcad4bdc4cfa&msgs=&mb=0&rt=1&search=inbox 404 ()
send @ VM19558:1
ajax @ VM19558:1
r.tools.make_request_async @ VM19558:1
r.get.email_data_async @ VM19558:1
r.get.displayed_email_data_async @ VM19558:1
(anonymous) @ VM22318:1
VM19558:1 Request Failed 
(anonymous) @ VM19558:1
s @ VM19558:1
fireWith @ VM19558:1
A @ VM19558:1
(anonymous) @ VM19558:1
XMLHttpRequest.send (async)
send @ VM19558:1
ajax @ VM19558:1
r.tools.make_request_async @ VM19558:1
r.get.email_data_async @ VM19558:1
r.get.displayed_email_data_async @ VM19558:1
(anonymous) @ VM22318:1
gmail.get.displayed_email_data_async(gmail.get.curr)
undefined
VM19558:1 GET https://mail.google.com/mail/u/0/?ui=2&ik=&rid=undefined&view=cv&th=1621dcad4bdc4cfa&msgs=&mb=0&rt=1&search=inbox 404 ()
send @ VM19558:1
ajax @ VM19558:1
r.tools.make_request_async @ VM19558:1
r.get.email_data_async @ VM19558:1
r.get.displayed_email_data_async @ VM19558:1
(anonymous) @ VM22401:1
VM19558:1 Request Failed 
(anonymous) @ VM19558:1
s @ VM19558:1
fireWith @ VM19558:1
A @ VM19558:1
(anonymous) @ VM19558:1
XMLHttpRequest.send (async)
send @ VM19558:1
ajax @ VM19558:1
r.tools.make_request_async @ VM19558:1
r.get.email_data_async @ VM19558:1
r.get.displayed_email_data_async @ VM19558:1
(anonymous) @ VM22401:1
gmail.get.displayed_email_data_async(gmail.get.current_page())
undefined
VM19558:1 GET https://mail.google.com/mail/u/0/?ui=2&ik=&rid=undefined&view=cv&th=1621dcad4bdc4cfa&msgs=&mb=0&rt=1&search=inbox 404 ()
send @ VM19558:1
ajax @ VM19558:1
r.tools.make_request_async @ VM19558:1
r.get.email_data_async @ VM19558:1
r.get.displayed_email_data_async @ VM19558:1
(anonymous) @ VM22416:1
VM19558:1 Request Failed 
(anonymous) @ VM19558:1
s @ VM19558:1
fireWith @ VM19558:1
A @ VM19558:1
(anonymous) @ VM19558:1
XMLHttpRequest.send (async)
send @ VM19558:1
ajax @ VM19558:1
r.tools.make_request_async @ VM19558:1
r.get.email_data_async @ VM19558:1
r.get.displayed_email_data_async @ VM19558:1
(anonymous) @ VM22416:1
gmail.get.displayed_email_data_async)
VM22640:1 Uncaught SyntaxError: Unexpected token )
gmail.get.displayed_email_data_async()
undefined
VM19558:1 GET https://mail.google.com/mail/u/0/?ui=2&ik=&rid=undefined&view=cv&th=1621dcad4bdc4cfa&msgs=&mb=0&rt=1&search=inbox 404 ()
send @ VM19558:1
ajax @ VM19558:1
r.tools.make_request_async @ VM19558:1
r.get.email_data_async @ VM19558:1
r.get.displayed_email_data_async @ VM19558:1
(anonymous) @ VM22653:1
VM19558:1 Request Failed 
(anonymous) @ VM19558:1
s @ VM19558:1
fireWith @ VM19558:1
A @ VM19558:1
(anonymous) @ VM19558:1
XMLHttpRequest.send (async)
send @ VM19558:1
ajax @ VM19558:1
r.tools.make_request_async @ VM19558:1
r.get.email_data_async @ VM19558:1
r.get.displayed_email_data_async @ VM19558:1
(anonymous) @ VM22653:1
gmail.get.email_id()
"1621dcad4bdc4cfa"
gmail.get.email_data
ƒ (e){var t=r.helper.get.email_data_pre(e);if(null!==t){var n=r.tools.make_request(t);return r.helper.get.email_data_post(n)}return{}}
gmail.get.email_data()
VM19558:1 GET https://mail.google.com/mail/u/0/?ui=2&ik=&rid=undefined&view=cv&th=1621dcad4bdc4cfa&msgs=&mb=0&rt=1&search=inbox 404 ()
send @ VM19558:1
ajax @ VM19558:1
r.tools.make_request @ VM19558:1
r.get.email_data @ VM19558:1
(anonymous) @ VM22846:1
VM22847:2 Uncaught SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.r.helper.get.email_data_post (<anonymous>:1:151070)
    at Object.r.get.email_data (<anonymous>:1:151289)
    at <anonymous>:1:11
r.helper.get.email_data_post @ VM19558:1
r.get.email_data @ VM19558:1
(anonymous) @ VM22846:1`

https://ibb.co/eugF9c

**Comment by josteink** [comment]
This seems like an issue with gmailjs itself. I suggest filing the issue there.
