### ISSUE TITLE
In compose,   compose.body() undefined

### ISSUE THREAD

**Issue by gayanku** [josteink/gmailjs-node-boilerplate#31]
I am not getting the object dom calls in the compose. See following code.

`
gmail.observe.on("compose", (compose) => {
            console.log("___New compose window is opened!", compose);

            compose.body('<h1>AAAA</H1>');
            console.log("body", compose.body);
            console.log("body()", compose.body());
});
`

![image](https://user-images.githubusercontent.com/86588503/218596110-30c970ba-73e1-4bc8-83c6-523f2743b98e.png)

body() is undefined.

**Comment by josteink** [comment]
This is an issue with gmail.js, not the boilerplate. Please file report in appropriate repo 🙂
