### ISSUE TITLE
Things to do to make an extension using the boilerplate production ready?

### ISSUE THREAD

**Issue by faisalsayed10** [josteink/gmailjs-node-boilerplate#32]
Are there any specific suggested changes that I should make in order to make my extension production ready?

**Comment by josteink** [comment]
Not unless you have any specific needs and it works for you?

You may not want to expose the Gmail object plainly in the DOM? You may want to preload to a namespace “owned” by your extension?

Your call.

**Comment by faisalsayed10** [comment]
got it, thanks!
