### ISSUE TITLE
"view_email" event fires twice

### ISSUE THREAD

**Issue by kaeevans** [josteink/gmailjs-node-boilerplate#35]
This is probably a bug with gmail.js, but I figured I'd ask here just in case it's somehow related to this repo.

**Issue:**
"view_email" fires twice when I open an email from the inbox.
I am using the unmodified boilerplate code.

**Solution tried:**
I followed the debugging instructions in [issue 526](https://github.com/KartikTalwar/gmail.js/issues/526) and confirmed that the "view_email" event-handler is only registered once. The call stack is the same each time "view_email" fires:
<img width="300" alt="IMG_7012" src="https://github.com/josteink/gmailjs-node-boilerplate/assets/3758445/4915db15-c920-4776-9b13-0f8a76f41b72">

Have you seen this before? Do you know what might be causing it?

**Comment by josteink** [comment]
Thanks for the report.

Not to be dismissive, but I'm closing this issue here as not related to gmailjs-boilerplate, and I see you already have an issue registered on gmail.js, where it should be :smile:
